server:
  port: 8080

#spring:
#  application:
#    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: auth-service-route
#          uri: http://localhost:8082
#          predicates:
#            - Path=/api/auth/**
#
#        - id: user-service-route
#          uri: http://localhost:8081
#          predicates:
#            - Path=/api/users/**
#
#
#        - id: card-service-route
#          uri: http://localhost:8083
#          predicates:
#            - Path=/api/cards/**
#
#
#        - id: product-service-route
#          uri: http://localhost:8084
#          predicates:
#            - Path=/api/products/**
#
#
#        - id: payment-service-route
#          uri: http://localhost:8085
#          predicates:
#            - Path=/api/payments/**


jwt:
  secret: ee1f5014e7ef2f84d1b179cf7533e31e